# Generated by Django 5.0.3 on 2024-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.IntegerField(blank=True, verbose_name="Telegram ID"),
        ),
    ]
